services:
  - type: web
    name: openhands
    env: docker
    repo: https://github.com/enablerdao/OpenHands
    dockerfilePath: ./containers/app/Dockerfile
    envVars:
      - key: RUNTIME
        value: daytona
      - key: DAYTONA_API_KEY
        sync: false
      - key: LOG_ALL_EVENTS
        value: true
      - key: FILE_STORE
        value: local
      - key: FILE_STORE_PATH
        value: /.openhands-state
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_BASE_URL
        fromService:
          name: openhands
          type: web
          property: host
      - key: REACT_ARIA_NO_SSR
        value: true
    healthCheckPath: /
    plan: free
